
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Noa Chemama
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

   private ArrayList<Question> listeQuestions;
   
   
   private int indexQuestionCourante = 0;
   int nbJuste=0;
   int compteur=0; 
    public FenetreQuiz() {
        initComponents();
        listeQuestions = new ArrayList<>();
         listeQuestions.add(new Question("Quelle est la capitale de la France ?","Londres", "Paris", "Berlin", "Rome",2));
         listeQuestions.add(new Question("Combien font 3 × 4 ?","7", "12", "9", "14",2));
         listeQuestions.add(new Question("Quel est l'océan le plus grand ?","Atlantique", "Indien", "Arctique", "Pacifique",4));
         
       lblQuestion.setText(listeQuestions.get(0).getIntitule());
       btnRep1.setText(listeQuestions.get(0).getProposition1());  
        btnRep2.setText(listeQuestions.get(0).getProposition2());
         btnRep3.setText(listeQuestions.get(0).getProposition3());
          btnRep4.setText(listeQuestions.get(0).getProposition4());
         questionSuiv.setText("Commencer la partie");
         bonneRep.setText("BONNE REPONSE !!!!!");
         mauvaiseRep.setText("MAUVAISE REPONSE !!!!!!");
         bonneRep.setVisible(false);
         mauvaiseRep.setVisible(false);
         btnRep1.setVisible(false);
         btnRep2.setVisible(false);
         btnRep3.setVisible(false);
         btnRep4.setVisible(false);
         lblQuestion.setVisible(false);
         score.setVisible(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        bonneRep = new javax.swing.JLabel();
        mauvaiseRep = new javax.swing.JLabel();
        questionSuiv = new javax.swing.JButton();
        score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestion.setText("jLabel1");
        getContentPane().add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 240, 120));

        btnRep1.setText("jButton1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 171, -1, -1));

        btnRep2.setText("jButton2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 171, -1, -1));

        btnRep3.setText("jButton3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 231, -1, -1));

        btnRep4.setText("jButton4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 231, -1, -1));

        bonneRep.setText("jLabel1");
        getContentPane().add(bonneRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        mauvaiseRep.setText("jLabel2");
        getContentPane().add(mauvaiseRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        questionSuiv.setText("jButton1");
        questionSuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionSuivActionPerformed(evt);
            }
        });
        getContentPane().add(questionSuiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, 30));

        score.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        score.setText("jLabel1");
        getContentPane().add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 200, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        if (1 == listeQuestions.get(indexQuestionCourante).getIndexBonneReponse()) {
        bonneRep.setVisible(true); 
        nbJuste++;
    }else {
            mauvaiseRep.setVisible(true);
        }
        indexQuestionCourante++;
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
       if (2 == listeQuestions.get(indexQuestionCourante).getIndexBonneReponse()) {
        bonneRep.setVisible(true);
        nbJuste++;
    }else {
            mauvaiseRep.setVisible(true);
        }
       indexQuestionCourante++;
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        if (3 == listeQuestions.get(indexQuestionCourante).getIndexBonneReponse()) {
        bonneRep.setVisible(true);   
        nbJuste++;
    }else {
            mauvaiseRep.setVisible(true);
        }
        indexQuestionCourante++;
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        if (4 == listeQuestions.get(indexQuestionCourante).getIndexBonneReponse()) {
        bonneRep.setVisible(true); 
        nbJuste++;
    }else {
            mauvaiseRep.setVisible(true);
        }
        indexQuestionCourante++;
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void questionSuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionSuivActionPerformed
       compteur++;
          if (compteur==4){
              compteur=compteur-1;
            score.setVisible(true);
            bonneRep.setVisible(false);
            mauvaiseRep.setVisible(false);
            btnRep1.setVisible(false);
            btnRep2.setVisible(false);
            btnRep3.setVisible(false);
            btnRep4.setVisible(false);
            lblQuestion.setVisible(false);
            score.setText("score :" + nbJuste  +"/" + indexQuestionCourante );
          
          }else{
          
        questionSuiv.setText("Question Suivante");
        btnRep1.setVisible(true);
         btnRep2.setVisible(true);
         btnRep3.setVisible(true);
         btnRep4.setVisible(true);
         lblQuestion.setVisible(true);
        bonneRep.setVisible(false);
        mauvaiseRep.setVisible(false);
         lblQuestion.setText(listeQuestions.get(indexQuestionCourante).getIntitule());
       btnRep1.setText(listeQuestions.get(indexQuestionCourante).getProposition1());  
        btnRep2.setText(listeQuestions.get(indexQuestionCourante).getProposition2());
         btnRep3.setText(listeQuestions.get(indexQuestionCourante).getProposition3());
          btnRep4.setText(listeQuestions.get(indexQuestionCourante).getProposition4());
          
          }
    }//GEN-LAST:event_questionSuivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bonneRep;
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel mauvaiseRep;
    private javax.swing.JButton questionSuiv;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
